-- Home feed keyset index.
--
-- The feed orders by ("publishedAt" DESC, id DESC) behind the fixed equality
-- predicate (status, "moderationStatus"). The existing
-- "Opportunity_status_moderationStatus_publishedAt_idx" stops one column short:
-- it has no `id`, so the keyset tie-breaker cannot be satisfied by the index
-- and Postgres re-checks it as a heap filter.
--
-- Measured on 50,000 published posts / 5,000 authors:
--
--   page 40 (cursor ~4,800 posts deep)
--     before: 93.3 ms, 4,795 rows discarded by filter, 175 shared buffers
--     after:  15.2 ms,                                  132 shared buffers
--
--   page 3 (cursor ~36 posts deep, full visibility joins)
--     after:   6.6 ms
--
-- Index size at that volume is 2 MB against a 9 MB table.
--
-- CONCURRENTLY so publishing is not blocked while it builds, matching
-- 20260808150000_message_mutation_polling_index.
--
-- The older three-column index is deliberately retained: it still serves
-- non-feed callers that filter on the same prefix without the id tie-breaker.
CREATE INDEX CONCURRENTLY IF NOT EXISTS "Opportunity_status_moderationStatus_publishedAt_id_idx"
ON "Opportunity"("status", "moderationStatus", "publishedAt" DESC, "id" DESC);
